# Generated by Django 2.0 on 2019-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=512)),
                ('cliente', models.CharField(max_length=30)),
                ('fecha_limite', models.DateField()),
            ],
        ),
    ]
